### ISSUE TITLE
Excuse me Thor, I ordered 100,000 sats and got promised 1,000,000 instead

### ISSUE THREAD

**Issue by maximlomans** [bitrefill/thor-api-doc#2]
... Xmas is not for another 10mnts.
Obviously the channel creation failed too, RTL says there's not enough funds to open a channel with 1mln sats.
 
I asked support via email to explain this confounding experience, which seems to be the regular behavior of Thor BTC count - never got it replied, and Docs mention nothing related to BTC count, or anything specific  pertaining to lighting network vouchers.
 - no matter how abstract the lightning network might seem, one shouldn't have to  scratch his head over is a simple straight-up order ; 

1 chicken remains one chicken, no matter where you order it, right ?

So how does 50euro worth of BTC, which at current price is exactly 129,676 sats,

equate to 1,000,000 sats,  worth, 1000 euros+  ?

**Comment by ziggamon** [comment]
I think you're referring to channel capacity. In the thor channel the channel capacity is on our end. You don't actually receive sats, just an "empty" channel so that you can later receive sats

**Comment by maximlomans** [comment]
OK .
thank you
